### ISSUE TITLE
[isabelle] IPv6 Support

### ISSUE THREAD

**Issue by diekmann** [diekmann/Iptables_Semantics#55]
Title says everything. This shouldn't be too hard, most internals already work on machine words of arbitrary length. Most complicated part will probably be the toString and fromString functions because IPv6 address notation is significantly more complex than IPv4 dotted-decimal. Yes, we also want this to be formally verified :-)

**Comment by diekmann** [comment]
"This shouldn't be too hard" he said, ...
Still working on it

**Comment by diekmann** [comment]
Generalized most of the thy to machine words of arbitrary length. Still working on global IPv6 support.

**Comment by diekmann** [comment]
`fffuu6` processed `net-network/configs_chair_for_Network_Architectures_and_Services/ip6tables-save-2016-06-27_16-29-01` in 33min. Given that this more than 6k ipv6 rules (!!!), that's not so bad.

Still need to
  * write test cases (I just have proven everything, not yet tested)
  * Add reliable test cases and examples in thy
  * document
  * merge to master
  * set up bintray deployment
  * build a cardboard castle as defend against angry @larsrh once he finds out how I accomplished IPv6 support (commit 7a8c29be346230fa5848397dc626d4d8171ef58f)

**Comment by larsrh** [comment]
![82hd6](https://cloud.githubusercontent.com/assets/923079/16759250/4a488f6a-4816-11e6-8314-128e8df8f856.jpg)

**Comment by diekmann** [comment]
IPv6 support now in master.

Still need to

 * write test cases for fffuu
 * add documentation
 * set up bintray deployment or only create one binary which can do both ipv4 and ipv6
