### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ericnyamu** [diekmann/Iptables_Semantics#8]
Hi.here's my situation.i have some computers that are behind a nat.i would like to pass this 'natting ip' through a vpn,so that all the pc behind the nat can be using the vpn.how should the iptables commands look like.The vpn interface is tun0 and the natting interface is eth0.thanks

**Comment by larsrh** [comment]
This is not a mailing list or discussion forum about iptables, it is the issue tracker for a formalization of iptables. Considering the bunch of other projects where you asked the exact same question, please refrain from posting here, unless you want to report an issue with the formalization.

**Comment by diekmann** [comment]
Dear ericnyamu, spamming all sorts of projects with this question is not helpful!

If you want to formalize and verify your iptables setup: Semantics.thy clearly states that packet modification is not supported.
